artifact_location: file:///e:/Project/Health-Insurance-Cost-Predictor/mlruns_Charges/858796445197747756
creation_time: 1768754382650
experiment_id: '858796445197747756'
last_update_time: 1768754382650
lifecycle_stage: active
name: Medical Insurance Charges
