artifact_location: file:///e:/Project/Health-Insurance-Cost-Predictor/mlruns_Charges/0
creation_time: 1768754382619
experiment_id: '0'
last_update_time: 1768754382619
lifecycle_stage: active
name: Default
